// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/parseLotuses.ts

import type { LotusEffect } from '../types';

export const LOTUSES: LotusEffect[] = [
  {
    "id": "adds-1-bubble",
    "name": "Adds 1 bubble",
    "description": "Adds 1 bubble",
    "effect": {
      "type": "add",
      "count": 1
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-2-bubbles",
    "name": "Adds 2 bubbles",
    "description": "Adds 2 bubbles",
    "effect": {
      "type": "add",
      "count": 2
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-3-bubbles",
    "name": "Adds 1-3 bubbles",
    "description": "Adds 1-3 bubbles",
    "effect": {
      "type": "add",
      "count": [
        1,
        3
      ]
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-bubble-that-is-blue-or-better",
    "name": "Adds 1 bubble that is Blue or better",
    "description": "Adds 1 bubble that is Blue or better",
    "effect": {
      "type": "add",
      "count": 1,
      "quality": "blue_or_better"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-2-bubbles-that-are-blue-or-better",
    "name": "Adds 2 bubbles that are Blue or better",
    "description": "Adds 2 bubbles that are Blue or better",
    "effect": {
      "type": "add",
      "count": 2,
      "quality": "blue_or_better"
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-3-bubbles-that-are-blue-or-better",
    "name": "Adds 1-3 bubbles that are Blue or better",
    "description": "Adds 1-3 bubbles that are Blue or better",
    "effect": {
      "type": "add",
      "count": [
        1,
        3
      ],
      "quality": "blue_or_better"
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-bubble-that-is-purple-or-better",
    "name": "Adds 1 bubble that is Purple or better",
    "description": "Adds 1 bubble that is Purple or better",
    "effect": {
      "type": "add",
      "count": 1,
      "quality": "purple_or_better"
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-2-bubbles-that-are-purple-or-better",
    "name": "Adds 2 bubbles that are Purple or better",
    "description": "Adds 2 bubbles that are Purple or better",
    "effect": {
      "type": "add",
      "count": 2,
      "quality": "purple_or_better"
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-3-bubbles-that-are-purple-or-better",
    "name": "Adds 1-3 bubbles that are Purple or better",
    "description": "Adds 1-3 bubbles that are Purple or better",
    "effect": {
      "type": "add",
      "count": [
        1,
        3
      ],
      "quality": "purple_or_better"
    },
    "nightmareOmen": "Significant difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-bubble-that-is-the-same-quality-as-the-highest-quality-bubble-you-own-including-rainbow",
    "name": "Adds 1 bubble that is the same quality as the high",
    "description": "Adds 1 bubble that is the same quality as the highest-quality bubble you own (including Rainbow)",
    "effect": {
      "type": "add",
      "count": 1,
      "quality": "Rainbow"
    },
    "nightmareOmen": "Significant difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-2-bubbles-that-are-the-same-quality-as-the-highest-quality-bubble-you-own-including-rainbow",
    "name": "Adds 2 bubbles that are the same quality as the hi",
    "description": "Adds 2 bubbles that are the same quality as the highest-quality bubble you own (including Rainbow)",
    "effect": {
      "type": "add",
      "count": 2,
      "quality": "Rainbow"
    },
    "nightmareOmen": "Major difficulty increase",
    "isFundamental": false
  },
  {
    "id": "upgrades-the-quality-of-1-bubble-by-1-tier",
    "name": "Upgrades the quality of 1 bubble by 1 tier",
    "description": "Upgrades the quality of 1 bubble by 1 tier",
    "effect": {
      "type": "upgrade",
      "count": 1,
      "tiers": 1
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "upgrades-the-quality-of-1-bubble-by-2-tiers",
    "name": "Upgrades the quality of 1 bubble by 2 tiers",
    "description": "Upgrades the quality of 1 bubble by 2 tiers",
    "effect": {
      "type": "upgrade",
      "count": 1,
      "tiers": 2
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "upgrades-the-quality-of-1-bubble-by-3-tiers",
    "name": "Upgrades the quality of 1 bubble by 3 tiers",
    "description": "Upgrades the quality of 1 bubble by 3 tiers",
    "effect": {
      "type": "upgrade",
      "count": 1,
      "tiers": 3
    },
    "nightmareOmen": "Significant difficulty increase",
    "isFundamental": false
  },
  {
    "id": "randomly-selects-1-bubble-to-replicate",
    "name": "Randomly selects 1 bubble to replicate",
    "description": "Randomly selects 1 bubble to replicate",
    "effect": {
      "type": "replicate",
      "count": 1
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "randomly-selects-2-bubbles-to-replicate",
    "name": "Randomly selects 2 bubbles to replicate",
    "description": "Randomly selects 2 bubbles to replicate",
    "effect": {
      "type": "replicate",
      "count": 2
    },
    "nightmareOmen": "Significant difficulty increase",
    "isFundamental": false
  },
  {
    "id": "randomly-selects-1-3-bubbles-to-replicate",
    "name": "Randomly selects 1-3 bubbles to replicate",
    "description": "Randomly selects 1-3 bubbles to replicate",
    "effect": {
      "type": "replicate",
      "count": 3
    },
    "nightmareOmen": "Significant difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-gear-bubble",
    "name": "Adds 1 Gear Bubble",
    "description": "Adds 1 Gear Bubble",
    "effect": {
      "type": "add",
      "count": 1,
      "bubbleType": "Gear"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-2-gear-bubbles",
    "name": "Adds 2 Gear Bubbles",
    "description": "Adds 2 Gear Bubbles",
    "effect": {
      "type": "add",
      "count": 2,
      "bubbleType": "Gear"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-3-gear-bubbles",
    "name": "Adds 1-3 Gear Bubbles",
    "description": "Adds 1-3 Gear Bubbles",
    "effect": {
      "type": "add",
      "count": [
        1,
        3
      ],
      "bubbleType": "Gear"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-gear-bubble-that-is-blue-or-better",
    "name": "Adds 1 Gear Bubble that is Blue or better",
    "description": "Adds 1 Gear Bubble that is Blue or better",
    "effect": {
      "type": "add",
      "count": 1,
      "quality": "blue_or_better",
      "bubbleType": "Gear"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-2-gear-bubbles-that-are-blue-or-better",
    "name": "Adds 2 Gear Bubbles that are Blue or better",
    "description": "Adds 2 Gear Bubbles that are Blue or better",
    "effect": {
      "type": "add",
      "count": 2,
      "quality": "blue_or_better",
      "bubbleType": "Gear"
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-3-gear-bubbles-that-are-blue-or-better",
    "name": "Adds 1-3 Gear Bubbles that are Blue or better",
    "description": "Adds 1-3 Gear Bubbles that are Blue or better",
    "effect": {
      "type": "add",
      "count": [
        1,
        3
      ],
      "quality": "blue_or_better",
      "bubbleType": "Gear"
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-gear-bubble-that-is-purple-or-better",
    "name": "Adds 1 Gear Bubble that is Purple or better",
    "description": "Adds 1 Gear Bubble that is Purple or better",
    "effect": {
      "type": "add",
      "count": 1,
      "quality": "purple_or_better",
      "bubbleType": "Gear"
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-2-gear-bubble-that-is-purple-or-better",
    "name": "Adds 2 Gear Bubble that is Purple or better",
    "description": "Adds 2 Gear Bubble that is Purple or better",
    "effect": {
      "type": "add",
      "count": 2,
      "quality": "purple_or_better",
      "bubbleType": "Gear"
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-3-gear-bubbles-that-are-purple-or-better",
    "name": "Adds 1-3 Gear Bubbles that are Purple or better",
    "description": "Adds 1-3 Gear Bubbles that are Purple or better",
    "effect": {
      "type": "add",
      "count": [
        1,
        3
      ],
      "quality": "purple_or_better",
      "bubbleType": "Gear"
    },
    "nightmareOmen": "Significant difficulty increase",
    "isFundamental": false
  },
  {
    "id": "changes-the-type-of-1-bubble-to-gear",
    "name": "Changes the type of 1 bubble to Gear",
    "description": "Changes the type of 1 bubble to Gear",
    "effect": {
      "type": "changeType",
      "count": 1,
      "newType": "Gear",
      "upgradeAfter": false
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "changes-the-type-of-2-bubbles-to-gear",
    "name": "Changes the type of 2 bubbles to Gear",
    "description": "Changes the type of 2 bubbles to Gear",
    "effect": {
      "type": "changeType",
      "count": 2,
      "newType": "Gear",
      "upgradeAfter": false
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "changes-the-type-of-3-bubbles-to-gear",
    "name": "Changes the type of 3 bubbles to Gear",
    "description": "Changes the type of 3 bubbles to Gear",
    "effect": {
      "type": "changeType",
      "count": 3,
      "newType": "Gear",
      "upgradeAfter": false
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "changes-the-type-of-1-bubble-to-gear-and-then-upgrades-its-quality-by-1-tier",
    "name": "Changes the type of 1 bubble to Gear, and then upg",
    "description": "Changes the type of 1 bubble to Gear, and then upgrades its quality by 1 tier",
    "effect": {
      "type": "upgrade",
      "count": 1,
      "tiers": 1
    },
    "nightmareOmen": "Moderate difficulty increase",
    "isFundamental": false
  },
  {
    "id": "changes-the-type-of-2-bubbles-to-gear-and-upgrades-their-quality-by-1-tier",
    "name": "Changes the type of 2 bubbles to Gear and upgrades",
    "description": "Changes the type of 2 bubbles to Gear and upgrades their quality by 1 tier",
    "effect": {
      "type": "upgrade",
      "count": 1,
      "tiers": 1
    },
    "nightmareOmen": "Significant difficulty increase",
    "isFundamental": false
  },
  {
    "id": "removes-1-bubble-and-then-upgrades-the-quality-of-1-bubble-by-4-tiers",
    "name": "Removes 1 bubble and then upgrades the quality of ",
    "description": "Removes 1 bubble and then upgrades the quality of 1 bubble by 4 tiers",
    "effect": {
      "type": "upgrade",
      "count": 1,
      "tiers": 4
    },
    "nightmareOmen": "Significant difficulty increase",
    "isFundamental": false
  },
  {
    "id": "removes-1-bubble-and-then-upgrades-the-quality-of-2-bubbles-by-2-tiers",
    "name": "Removes 1 bubble and then upgrades the quality of ",
    "description": "Removes 1 bubble and then upgrades the quality of 2 bubbles by 2 tiers",
    "effect": {
      "type": "upgrade",
      "count": 2,
      "tiers": 2
    },
    "nightmareOmen": "Significant difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-blacksail-bubble",
    "name": "Adds 1 Blacksail Bubble",
    "description": "Adds 1 Blacksail Bubble",
    "effect": {
      "type": "add",
      "count": 1,
      "bubbleType": "Blacksail"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-cube-bubble",
    "name": "Adds 1 Cube Bubble",
    "description": "Adds 1 Cube Bubble",
    "effect": {
      "type": "add",
      "count": 1,
      "bubbleType": "Cube"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-commodity-bubble",
    "name": "Adds 1 Commodity Bubble",
    "description": "Adds 1 Commodity Bubble",
    "effect": {
      "type": "add",
      "count": 1,
      "bubbleType": "Commodity"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-netherrealm-bubble",
    "name": "Adds 1 Netherrealm Bubble",
    "description": "Adds 1 Netherrealm Bubble",
    "effect": {
      "type": "add",
      "count": 1,
      "bubbleType": "Netherrealm"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-fluorescent-bubble",
    "name": "Adds 1 Fluorescent Bubble",
    "description": "Adds 1 Fluorescent Bubble",
    "effect": {
      "type": "add",
      "count": 1,
      "bubbleType": "Fluorescent"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  },
  {
    "id": "adds-1-whim-bubble",
    "name": "Adds 1 Whim Bubble",
    "description": "Adds 1 Whim Bubble",
    "effect": {
      "type": "add",
      "count": 1,
      "bubbleType": "Whim"
    },
    "nightmareOmen": "Minor difficulty increase",
    "isFundamental": false
  }
];

// Total lotuses: 39
